# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddReader.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddbookWindow(object):
    def setupUi(self, AddbookWindow):
        AddbookWindow.setObjectName("AddbookWindow")
        AddbookWindow.resize(416, 330)
        self.centralwidget = QtWidgets.QWidget(AddbookWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 20, 341, 391))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.SecondNameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.SecondNameEdit.setObjectName("SecondNameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.SecondNameEdit)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.NameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.NameEdit.setObjectName("NameEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.NameEdit)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.FathernameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.FathernameEdit.setObjectName("FathernameEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.FathernameEdit)
        self.CancelButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.CancelButton.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CancelButton.setFont(font)
        self.CancelButton.setObjectName("CancelButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.CancelButton)
        self.InsertButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InsertButton.setFont(font)
        self.InsertButton.setObjectName("InsertButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.InsertButton)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.AdresEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.AdresEdit.setObjectName("AdresEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.AdresEdit)
        AddbookWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddbookWindow)
        self.statusbar.setObjectName("statusbar")
        AddbookWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddbookWindow)
        QtCore.QMetaObject.connectSlotsByName(AddbookWindow)

    def retranslateUi(self, AddbookWindow):
        _translate = QtCore.QCoreApplication.translate
        AddbookWindow.setWindowTitle(_translate("AddbookWindow", "Добавить"))
        self.label_3.setText(_translate("AddbookWindow", "Фамилия"))
        self.label_4.setText(_translate("AddbookWindow", "Имя"))
        self.label_5.setText(_translate("AddbookWindow", "Отчество"))
        self.CancelButton.setText(_translate("AddbookWindow", "Отмена"))
        self.InsertButton.setText(_translate("AddbookWindow", "Внести данные"))
        self.label_6.setText(_translate("AddbookWindow", "Адрес"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    AddbookWindow = QtWidgets.QMainWindow()
    ui = Ui_AddbookWindow()
    ui.setupUi(AddbookWindow)
    AddbookWindow.show()
    sys.exit(app.exec_())
